---
- name: Dar privilegios sudo al grupo GProfesores
  copy:
    dest: /etc/sudoers.d/gprofesores
    content: "%GProfesores ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'

- name: Dar privilegios sudo al grupo GAlumnos
  copy:
    dest: /etc/sudoers.d/galumnos
    content: "%GAlumnos ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'
