---

- name: Crear carpeta /UTN
  file:
    path: /UTN
    state: directory
    mode: '0755'

- name: Crear carpeta /UTN/Profesor
  file:
    path: /UTN/Profesor
    state: directory
    owner: Profesor
    group: GProfesores
    mode: '0750'

- name: Crear carpeta /UTN/Alumno
  file:
    path: /UTN/Alumno
    state: directory
    owner: alumno
    group: GAlumnos
    mode: '0750'
