- name: Ejecucion de Tareas del Recuperatorio 2do Parcial
  hosts: localhost
  connection: local
  become: yes

  roles:
    - 2PRecuperatorio
    - Crea_Carpetas_TD
    - Cambia_Propiedad_TD
    - Sudoers_TD  
