---
- name: 1. Crear grupos GProfesores y GAlumnos
  group:
    name: "{{ item }}"
    state: present
  loop:
    - GProfesores
    - GAlumnos

- name: 2. Crear usuario Profesor y asignarlo a GProfesores
  user:
    name: Profesor
    state: present
    groups: GProfesores
    append: yes 

- name: 3. Crear usuario alumno y asignarlo a GAlumnos
  user:
    name: alumno
    state: present
    groups: GAlumnos
    append: yes
